$(document).ready(function(){
    $(".close").click(function(){
        $("#ExemploModalCentralizado").empty();
    });
});
$(document).ready(function(){
    $(".close1").click(function(){
        $("#video1").empty();
    });
});
$(document).ready(function(){
    $(".close2").click(function(){
        $("#video2").empty();
    });
});
$(document).ready(function(){
    $(".close3").click(function(){
        $("#video3").empty();
    });
});
$(document).ready(function(){
    $(".close4").click(function(){
        $("#video4").empty();
    });
});
$(document).ready(function(){
    $(".close5").click(function(){
        $("#video5").empty();
    });
});
$(document).ready(function(){
    $(".close6").click(function(){
        $("#video6").empty();
    });
});
$(document).ready(function(){
    $(".close7").click(function(){
        $("#video7").empty();
    });
});
$(document).ready(function(){
    $(".close8").click(function(){
        $("#video8").empty();
    });
});
$(document).ready(function(){
    $(".close9").click(function(){
        $("#video9").empty();
    });
});