$(document).ready(function(){
    $(".close").click(function(){
        $("#ExemploModalCentralizado").empty();
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $("#video1").empty();
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $("#video2").empty();
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $("#video3").empty();
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $("#video4").empty();
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $("#video5").empty();
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $("#video6").empty();
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $("#video7").empty();
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $("#video8").empty();
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $("#video9").empty();
    });
});